name: Create Release on Push to Main

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: true

      - name: Initialize submodules
        run: git submodule update --init --recursive            

      # Create a basic versioning scheme using the latest commit SHA
      - name: Get Version
        id: get_version
        run: |
          # Versioning. For simplicity, use the latest commit SHA
          VERSION=$(git rev-parse --short HEAD)
          echo "version=$VERSION" >> $GITHUB_ENV

      # Create a GitHub release
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: Release ${{ env.version }}
          draft: false
          prerelease: false
